# Generated by Django 5.2.4 on 2025-08-06 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('select', 'Select an Event'), ('conference', 'Conference'), ('webinar', 'Webinar'), ('meet_and_greet', 'Meet and Greet'), ('hackathon', 'Hackathon'), ('coding_bootcamp', 'Coding BootCamp'), ('movie_night', 'Movie Night'), ('r_n_b_night', 'RnB Night'), ('pack_and_chill', 'Pack and Chill'), ('pack_and_grill', 'Pack and Grill'), ('others', 'Others')], max_length=120)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'ongoing'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('is_public', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
