# Generated by Django 5.2.4 on 2025-08-19 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookEvent',
        ),
    ]
