# Generated by Django 5.2.4 on 2025-08-24 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_like_delete_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('select', 'Select an Event'), ('conference', 'Conference'), ('webinar', 'Webinar'), ('meet_and_greet', 'Meet and Greet'), ('hackerthon', 'Hackerthon'), ('coding_bootcamp', 'Coding BootCamp'), ('movie_night', 'Movie Night'), ('r_n_b_night', 'RnB Night'), ('pack_and_chill', 'Pack and Chill'), ('pack_and_grill', 'Pack and Grill'), ('festival', 'Festival'), ('exhibition', 'Exhibition'), ('sports', 'Sports'), ('workshop', 'Workshop'), ('others', 'Others')], max_length=120),
        ),
        migrations.CreateModel(
            name='BookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('booking_status', models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='Pending', max_length=100)),
                ('number_of_tickets', models.PositiveIntegerField(default=1)),
                ('payment_status', models.DecimalField(choices=[('select', 'Select Option'), ('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded')], decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='events.event')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_event', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
