# Generated by Django 5.2.4 on 2025-08-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_attendees_alter_bookevent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookevent',
            name='payment_status',
            field=models.CharField(choices=[('select', 'Select Option'), ('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded')], max_length=120),
        ),
    ]
