# Generated by Django 5.2.5 on 2025-08-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_bookevent_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_booking',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'ongoing'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('past', 'Past Events')], default='upcoming', max_length=120),
        ),
    ]
